### PR TITLE
Convert projects to dotnetcore2

### PR DESCRIPTION
**Pull request by davidvedvick**
This fixes Issue #2, adding support for dotnetcore2.

According to [the dotnet standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), this will increase the required .Net framework to .Net 4.6.1.

### CODE REVIEW

**Comment by provegard** [comment]
Sorry for not getting back to you - I have been on vacation.

I expected to see a new version of NUnit but not NSpec - why is the latter updated?

Furthermore, I'd like to target the same minimum .NET version as NSpec. [This file](https://github.com/nspec/NSpec/blob/master/BREAKING-CHANGES.md) indicates it's 4.5.2. [This file](https://github.com/nspec/NSpec/blob/master/sln/src/NSpec/project.json) lists .NET Standard 1.6 and .NET Framework 4.5.1 (though I don't really understand how that could work according to the version matrix you linked to).

I checked out this PR and added a classic .NET Framework 4.6.1 project in VS2017. Adding NSpec as reference to that project resulting in a lot of dependencies being added with warning triangles. Also, referencing the NSpecInNUnit project didn't help the base class with being recognized.

Next I added a classic .NET Framework 4.5.2 project but it's not allowed to reference the NSpecInNUnit project.

I guess multi targeting is the answer? Could you add support for that and make sure things work with 4.52? Also, please revert to the previous version of NSpec for now. Thanks!

**Comment by provegard** [comment]
Btw, NUnit should be at version 3.7, I think, since that's the first version where the bug that prevented .NET Core was fixed.

**Comment by danrien** [comment]
I'll see what I can do to multi-target frameworks.

NUnit's documentation states that version 3.8.0 is required for dotnetcore (https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard) - unless you're referring to something else?

**Comment by danrien** [comment]
I managed to safely downgrade NUnit to 3.7.0 and get multi-targeting working. However, when running with nspec 2.0 I got this error, so I left it at 3.1.0:

```
Test Name:	RealizeSpec
Test FullName:	NSpecInNUnit.cover.RealizeSpec
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

Result StackTrace:	
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
--MissingMethodException
   at NSpecInNUnit.nspec_as_nunit`1.Examples()
Result Message:	
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.MissingMethodException : Method not found: 'Void NSpec.Domain.Context..ctor(System.String, System.String, Boolean)'.

```

**Comment by provegard** [comment]
Thanks, I'll take a new look.

**Comment by provegard** [comment]
I merged the PR with some minor changes:

* Make sure NUnit 3.7 is used everywhere
* Add an example project for .NET 4.5.2
* Downgrade to NSpec 3.0.3 to be as compatible as possible, and because 3.1.0 introduces a lot of changes that I want to take a closer look at before going up.

I made a mention of you in the README (though I see now that your user profile isn't linked automatically - I'll fix that). Hope that's ok!

Many thanks for your contribution! :-)

**Comment by danrien** [comment]
Great, glad to be of help :)

**Pull request merged**
